In [1]:
import seaborn as sns
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import time
from datetime import datetime
from datetime import date

In [2]:
df1=pd.read_csv('../datasets/chelseapalacetweets.csv')
df2=pd.read_csv('../datasets/chelseapalacetweets2.csv')
df3=pd.read_csv('../datasets/chelseapalacetweets3.csv')
df4=pd.read_csv('../datasets/chelseapalacetweets4.csv')
df5=pd.read_csv('../datasets/chelseapalacetweets5.csv')
df6=pd.read_csv('../datasets/chelseapalacetweets6.csv')
df7=pd.read_csv('../datasets/chelseapalacetweets7.csv')

In [4]:
df=pd.concat([df1,df2,df3,df4,df5,df6,df7], axis=0, join='outer', ignore_index=True, verify_integrity=True)

In [5]:
df

,username,text,tweetcreatedts,hashtags,acctdesc,location,followers,totaltweets,usercreatedts,retweetcount
0,titomar_758,Chelsea vs Crystal palace. \n\n‚Ä¢ Mendy clean s...,2020-10-03 13:32:07,[],NaN,Canaries st.lucia,973,52301,2014-02-01 20:02:37,77
1,Kennyroja191,"Wait, this same Crystal Palace flogged Man Utd...",2020-10-03 13:32:07,[],NaN,"Osun, Nigeria",36,877,2019-12-30 17:20:58,59
2,John38466297,Seems like beating Crystal Palace at home this...,2020-10-03 13:32:07,[],NaN,"Maryland, Lagos",37,251,2020-07-15 11:37:58,994
3,damyyllare,üè¥Û†ÅßÛ†Å¢Û†Å•Û†ÅÆÛ†ÅßÛ†Åø Ben Chilwell vs Crystal Palace\n\n90 m...,2020-10-03 13:32:07,[],I am a blessing for my generation... I love fi...,Nigeria,416,4410,2016-03-15 12:51:50,65
4,Younguzumaki1,I love how Havertz constantly roams around the...,2020-10-03 13:32:06,[],NaN,"Federal Capital Territory, Nig",1346,50678,2012-07-21 15:12:44,7
...,...,...,...,...,...,...,...,...,...,...
14084,schoolBoyfrm5th,Ben Chilwell has lost possession (5) more time...,2020-10-03 13:14:15,[],yooohooooo\n bastard of the east blue,village hidden in the tits,1906,36980,2017-06-29 16:20:52,587
14085,Tamar__lee,Is this the crystal palace that beat Man U?,2020-10-03 13:14:14,[],"watched by angels.,protected by God",Nigeria,1006,18683,2012-12-06 17:06:31,0
14086,I_am_Tangeni,"Ano, TF is up with Palace? Can‚Äôt believe we go...",2020-10-03 13:14:14,['CHECRY'],"Beer Drinkers Hall of Fame, #Father #Son #Brot...",Namibia,1543,64100,2011-12-11 08:18:19,1
14087,Arsenal_LINY,It just keeps getting worst for Crystal Palace...,2020-10-03 13:14:13,['checry'],Supporting Arsenal Football Club #COYG,"Long Island, NY",386,11668,2016-12-11 18:32:21,0
14088,Independent,GOAL! Jorginho adds a second following row wit...,2020-10-03 13:14:13,"['CFC', 'CPFC']","News, comment and features from The Independen...","London, England",3343023,1035201,2008-10-26 00:00:29,4

In [12]:
df=df.loc[~df.duplicated()]

In [13]:
df

,username,text,tweetcreatedts,hashtags,acctdesc,location,followers,totaltweets,usercreatedts,retweetcount
0,titomar_758,Chelsea vs Crystal palace. \n\n‚Ä¢ Mendy clean s...,2020-10-03 13:32:07,[],NaN,Canaries st.lucia,973,52301,2014-02-01 20:02:37,77
1,Kennyroja191,"Wait, this same Crystal Palace flogged Man Utd...",2020-10-03 13:32:07,[],NaN,"Osun, Nigeria",36,877,2019-12-30 17:20:58,59
2,John38466297,Seems like beating Crystal Palace at home this...,2020-10-03 13:32:07,[],NaN,"Maryland, Lagos",37,251,2020-07-15 11:37:58,994
3,damyyllare,üè¥Û†ÅßÛ†Å¢Û†Å•Û†ÅÆÛ†ÅßÛ†Åø Ben Chilwell vs Crystal Palace\n\n90 m...,2020-10-03 13:32:07,[],I am a blessing for my generation... I love fi...,Nigeria,416,4410,2016-03-15 12:51:50,65
4,Younguzumaki1,I love how Havertz constantly roams around the...,2020-10-03 13:32:06,[],NaN,"Federal Capital Territory, Nig",1346,50678,2012-07-21 15:12:44,7
...,...,...,...,...,...,...,...,...,...,...
14084,schoolBoyfrm5th,Ben Chilwell has lost possession (5) more time...,2020-10-03 13:14:15,[],yooohooooo\n bastard of the east blue,village hidden in the tits,1906,36980,2017-06-29 16:20:52,587
14085,Tamar__lee,Is this the crystal palace that beat Man U?,2020-10-03 13:14:14,[],"watched by angels.,protected by God",Nigeria,1006,18683,2012-12-06 17:06:31,0
14086,I_am_Tangeni,"Ano, TF is up with Palace? Can‚Äôt believe we go...",2020-10-03 13:14:14,['CHECRY'],"Beer Drinkers Hall of Fame, #Father #Son #Brot...",Namibia,1543,64100,2011-12-11 08:18:19,1
14087,Arsenal_LINY,It just keeps getting worst for Crystal Palace...,2020-10-03 13:14:13,['checry'],Supporting Arsenal Football Club #COYG,"Long Island, NY",386,11668,2016-12-11 18:32:21,0
14088,Independent,GOAL! Jorginho adds a second following row wit...,2020-10-03 13:14:13,"['CFC', 'CPFC']","News, comment and features from The Independen...","London, England",3343023,1035201,2008-10-26 00:00:29,4

In [15]:
df.to_csv('../datasets/chelseapalacetweetscombined.csv',index=False)